version: "3.0"

services:
  db:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/pgdata/
      - POSTGRES_DB=shopdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - 5432:5432
  web:
    build: .
    volumes:
      - .:/src/
      - static:/static
      - media:/media
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: 'settings.base'


    command: /bin/bash -c "pip install -r requirements.txt && invoke run"


  ui:
    image: node:16.14.2
    volumes:
      - ./client:/src
    ports:
      - 3000:3000
    command: /bin/bash -c "cd /src/; npm i; npm run dev"


  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/static:ro
      - media:/media:ro
    links:
      - web
      - ui
    ports:
      - 80:80



volumes:
  pgdata: { }
  static: { }
  media: { }

