# Generated by Django 4.0.4 on 2022-05-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_author_birth_date_remove_author_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
